### ISSUE TITLE
Segfault on launch

### ISSUE THREAD

**Issue by ronnocnave** [nsg/snap-minecraft#1]
Hello. Running this snap on KDE Neon (16.04 LTS), I get a segfault on exec. No other information is provided. 

> james@james-neon:~/Downloads$ minecraft-nsg
> Segmentation fault

**Comment by nsg** [comment]
@ronnocnave what type of graphics card are you using? We have a know problem reported here https://github.com/konstructs/client/issues/210. We have been able to reproduce the bug on Intel graphics and I hope to push a fix for that within a day.

**Comment by nsg** [comment]
@ronnocnave can you check `/var/log/syslog` if apparmor is blocking anything on your system?

Lines that look like this:

```
Oct 24 00:36:48 narsil kernel: [190249.695888] audit: type=1400 audit(1477262208.839:208): apparmor="DENIED" operation="open" profile="snap.minecraft-nsg.minecraft-nsg" name="/proc/1783/net/if_inet6" pid=1784 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

**Comment by ronnocnave** [comment]
On 2016-10-23 6:37 pm, Stefan Berggren wrote:

> @ronnocnave [1] can you check /var/log/syslog if apparmor is blocking anything on your system? 
> 
> Lines that look like this:
> 
> Oct 24 00:36:48 narsil kernel: [190249.695888] audit: type=1400 audit(1477262208.839:208): apparmor="DENIED" operation="open" profile="snap.minecraft-nsg.minecraft-nsg" name="/proc/1783/net/if_inet6" pid=1784 comm="java" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

Hello again. Yes, that does appear to be the case. A log search turned
up the following lines: 

"james-neon kernel: [ 8482.945613] audit: type=1400
audit(1476992251.334:15): apparmor="DENIED" operation="file_mmap"
profile="snap.minecraft-nsg.minecraft-nsg"
name="/usr/lib/snapd/snap-exec" pid=4532 comm="snap-exec"
requested_mask="m" denied_mask="m" fsuid=1000 ouid=0
Oct 20 15:37:58 james-neon /usr/lib/snapd/snapd[4404]: daemon.go:174:
DEBUG: uid=1000;@ GET /v2/snaps 685.233µs 200
Oct 20 15:37:58 james-neon kernel: [ 8509.743315] audit: type=1400
audit(1476992278.132:16): apparmor="DENIED" operation="file_mmap"
profile="snap.minecraft-nsg.minecraft-nsg"
name="/usr/lib/snapd/snap-exec" pid=4556 comm="snap-exec"
requested_mask="m" denied_mask="m" fsuid=1000 ouid=0" 

So this appears to be a match to what you were suspecting. Hope that
helps. 
- James 

## Links:

[1] https://github.com/ronnocnave
[2]
https://github.com/nsg/snap-minecraft/issues/1#issuecomment-255619685
[3]

**Comment by ronnocnave** [comment]
On 2016-10-21 4:57 am, Stefan Berggren wrote:

> @ronnocnave [1] what type of graphics card are you using? We have a know problem reported here konstructs/client#210 [2]. We have been able to reproduce the bug on Intel graphics and I hope to push a fix for that within a day. 
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].

Hi. I am running an AMD R7 260x card with Radeon graphics. Let me know
if I can help further. 

## Links:

[1] https://github.com/ronnocnave
[2] https://github.com/konstructs/client/issues/210
[3]
https://github.com/nsg/snap-minecraft/issues/1#issuecomment-255329907
[4]

**Comment by nsg** [comment]
Have you been able to execute other opengl snap's? I'm considering some problem with your graphic driver and snapd. For example, the snap `ubuntu-calculator-app` requires opengl, do that work for you?

**Comment by nsg** [comment]
Closing old issue. If you still have a problem, feel free to open it again.
