### ISSUE TITLE
404 Error on Oracle Java download

### ISSUE THREAD

**Issue by ekandler** [nsg/snap-minecraft#2]
After a fresh installation of the snap, the application exits with the following log output;

> Download Oracle JDK to /home/erwin/snap/minecraft-nsg/5  
wget: Cannot read /etc/wgetrc (Permission denied).       
--2017-11-26 16:28:09--  http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz          
Resolving download.oracle.com (download.oracle.com)... 2.20.142.145, 2.20.142.137                                  
Connecting to download.oracle.com (download.oracle.com)|2.20.142.145|:80... Gtk-Message: Failed to load module "canberra-gtk-module"                                                                                                   
connected.                                               
HTTP request sent, awaiting response... Gtk-Message: Failed to load module "canberra-gtk-module"                   
302 Moved Temporarily                                    
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz [following]           
--2017-11-26 16:28:09--  https://edelivery.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz        
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.35.109.107, 2a02:26f0:10:583::2d3e, 2a02:26f0:10:5a1::2d3e                                                                                                                 
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.35.109.107|:443... connected.                         
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.                                     
HTTP request sent, awaiting response... 302 Moved Temporarily                                                      
Location: http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz?AuthParam=1511710209_0bfae2840ac632ff3c77287d65f1d072 [following]                                                                           
--2017-11-26 16:28:10--  http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-x64.tar.gz?AuthParam=1511710209_0bfae2840ac632ff3c77287d65f1d072                                                                        
Reusing existing connection to download.oracle.com:80.   
HTTP request sent, awaiting response... 404 Not Found    
2017-11-26 16:28:12 ERROR 404: Not Found.                

Seems like Oracle changed the download link for the jdk.

**Comment by nsg** [comment]
Indeed, I have fixed it in the edge channel and will release it i stable later today.

To try it, type `snap refresh minecraft-nsg --edge`

Changes:
* Change to Java 8u151
* Replace shell scripts with a nicer looking GTK3 UI for downloads
* Use the build services to publish the package

**Comment by nsg** [comment]
Released to stable channel, thank you for the report.

**Comment by NotJustPizza** [comment]
Reopen - same problem here
```
Downloading Oracle Java
--2018-07-21 23:34:40--  http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 2.17.156.119
Connecting to download.oracle.com (download.oracle.com)|2.17.156.119|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz [following]
--2018-07-21 23:34:41--  https://edelivery.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 104.102.3.223, 2a02:26f0:f:18e::2d3e, 2a02:26f0:f:19d::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|104.102.3.223|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1532209001_ca64ce4e69c2e721690216e05b91d03d [following]
--2018-07-21 23:34:41--  http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz?AuthParam=1532209001_ca64ce4e69c2e721690216e05b91d03d
Connecting to download.oracle.com (download.oracle.com)|2.17.156.119|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-21 23:34:43 ERROR 404: Not Found.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/snap/minecraft-nsg/13/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/snap/minecraft-nsg/13/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/snap/minecraft-nsg/13/download-java.py", line 84, in download_thread
    dh = hashlib.sha256(open(DOWNLOAD_FILE, 'rb').read()).hexdigest()
FileNotFoundError: [Errno 2] No such file or directory: 'jdk-8u151-linux-x64.tar.gz'
```

**Comment by Techcouncelor** [comment]
Mine just says ( Downloading Oracle Java ) but, it never even starts to download.

**Comment by nsg** [comment]
These days https://snapcraft.io/minecraft is probably a better supported snap, but I will update the snap with a new link.

**Comment by nsg** [comment]
I tried to update to latest java, but the launcher is getting stuck at "Starting launcher". I tried to replace Oracle Java with OpenJDK 8, same problem (you can try the `--edge` channel if you like to try it).

I'm not really sure what the problem is, but I have apparmor denials for `/proc/<pid>/net/if_inet6` and `/proc/<pid>/net/ipv6_route` ... not sure if this is something new or not.

The `minecraft` snap works for me, and it includes the new launcher. So I think I will recommend that you try that instead of this rather old legacy snap.

If you like to keep any local games, make sure to backup them *before* you remove this snap, and possible more it over to the minecraft snap.
